spring:
  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3336/HUNOSS_STANDARD
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost:3336/HUNOSS_STANDARD
    username: root
    password: admin123!@#
  jpa:
    open-in-view: false
server:
  servlet:
    session:
      cookie:
        name: HUNOSS_TOKEN
security:
  ignore-patterns: >
    /favicon.ico
  permit-all-patterns: >
    /api/agent/login/*,
    /api/agent/redirect/*
solupia:
  language:
    code: ko